version: "3"

services:
  web:
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    environment:
      DJANGO_DEBUG: "True"
      SECRET_KEY: ${SECRET_KEY}
      VRS_DOCKER_DB_HOST: "db"
      VRS_DOCKER_WEB_HOST: "web"
      VRS_DOCKER_DB: ${VRS_DOCKER_DB}
      VRS_DOCKER_DB_PWD: ${VRS_DOCKER_DB_PWD}
      VRS_DOCKER_DB_USER: ${VRS_DOCKER_DB_USER}

  nginx:
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    environment:
      VRS_DOCKER_WEB_HOST: "web"

  db:
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      VRS_DOCKER_DB_PWD: ${VRS_DOCKER_DB_PWD}
      VRS_DOCKER_DB_USER: ${VRS_DOCKER_DB_USER}

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend
