version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${VRS_DOCKER_DB_PWD}
      POSTGRES_USER: ${VRS_DOCKER_DB_USER}

  nginx:
    image: nginx:latest
    networks:
      - backend
    depends_on:
      - web

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${VRS_DOCKER_DB_PWD}
      POSTGRES_USER: ${VRS_DOCKER_DB_USER}
    networks:
     - backend

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
