# Generated by Django 2.2 on 2019-05-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRSGS1Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLN13', models.CharField(db_index=True, help_text='A GLN (Global Location Number) that represents a Location allowed to execute Verification Requests', max_length=13, null=True, unique=True, verbose_name='GLN13')),
                ('active', models.BooleanField(default=True, help_text='If the GLN13 is not Active, requests coming from the GLN, e.g. reqGLN=invalid_gtin, will be denied.', verbose_name='Active')),
            ],
            options={
                'db_table': 'quartet_vrs_glns',
            },
        ),
    ]
