# Generated by Django 3.0.2 on 2020-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VRSGS1Locations',
        ),
    ]
