# Generated by Django 2.2.6 on 2020-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0003_gtinmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(help_text='IP Address of the server making request.', max_length=14, null=True, verbose_name='Remote Address')),
                ('expiry', models.CharField(help_text='Expiry Query Parameter.', max_length=35, null=True, verbose_name='Expiry Date')),
                ('request_gln', models.CharField(help_text="Requestor's GLN.", max_length=13, null=True, verbose_name='Request GLN')),
                ('corr_uuid', models.CharField(help_text='The Correlation Unique Identifier, if used.', max_length=40, null=True, verbose_name='Correlation UUID')),
                ('gtin', models.CharField(help_text='GTIN Parameter Value for the request.', max_length=14, verbose_name='GTIN')),
                ('lot', models.CharField(help_text='Lot or Batch Parameter Value for the request.', max_length=150, null=True, verbose_name='Lot/Batch')),
                ('serial_number', models.CharField(help_text='Serial Number Parameter Value for the request.', max_length=50, null=True, verbose_name='Serial Number')),
                ('user_name', models.CharField(help_text='Name of user making the request.', max_length=100, verbose_name='User Name')),
                ('response', models.TextField(help_text='Response from the VRS.', verbose_name='Response Content')),
                ('method', models.CharField(help_text='The method, checkConnectivity or verify, called with this HTTP Request.', max_length=20, verbose_name='Method')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quartet_vrs_request_log',
            },
        ),
    ]
