# Generated by Django 2.2.6 on 2020-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0004_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='gtin',
            field=models.CharField(help_text='GTIN Parameter Value for the request.', max_length=14, null=True, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(help_text='The method, checkConnectivity or verify, called with this HTTP Request.', max_length=20, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response',
            field=models.TextField(help_text='Response from the VRS.', null=True, verbose_name='Response Content'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='user_name',
            field=models.CharField(help_text='Name of user making the request.', max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
