# Generated by Django 2.2.6 on 2020-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quartet_vrs', '0006_auto_20200203_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(null=True,
                                        max_length=50,
                                      help_text='The Request Type, checkConnectivity or verify, called with this HTTP Request.',
                                      verbose_name='Request Type'),
        ),

    ]
