# Generated by Django 2.2.6 on 2020-02-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0007_auto_20200203_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='response',
        ),
    ]
