# Generated by Django 2.2.6 on 2020-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0008_auto_20200203_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='operation',
            field=models.CharField(help_text='The API Operation Requested, checkConnectivity or verify, called with this HTTP Request.', max_length=50, null=True, verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response',
            field=models.TextField(help_text='Response from the VRS.', null=True, verbose_name='Response Content'),
        ),
    ]
