# Generated by Django 2.2.6 on 2020-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0009_auto_20200203_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtinmap',
            name='password',
            field=models.CharField(blank=True, db_index=True, help_text='The Password for the VRS Router.', max_length=100, null=True, unique=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='gtinmap',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, help_text='The Username for the VRS Router.', max_length=100, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='gtinmap',
            name='path',
            field=models.CharField(blank=True, help_text='The Sub Path of the VRS Service. For Example: If the URL path is http://vrs.qu4rtet.io/vrs, then the path is: /vrs', max_length=256, null=True, verbose_name='Path'),
        ),
    ]
