# Generated by Django 2.2.6 on 2020-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0010_auto_20200204_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtinmap',
            name='port',
            field=models.CharField(blank=True, help_text='Port Number to use when calling external VRS. NOTE: Port is NOT required when Port Number is 443 or 80', max_length=10, null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='gtinmap',
            name='host',
            field=models.CharField(help_text='The Hostname of the VRS Router. If the URL is https://vrs.qu4rtet.io, then the host is: vrs.qu4rtet.io.', max_length=256, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='gtinmap',
            name='path',
            field=models.CharField(blank=True, help_text='The Sub Path of the VRS Service. For Example: If the URL path is http://vrs.qu4rtet.io/vrs, then the path is: /vrs.The compliant portion of the path, e.g. /verify/ or /checkConnectivity, is NOT required here.', max_length=256, null=True, verbose_name='Path'),
        ),
    ]
