# Generated by Django 2.2.6 on 2020-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_vrs', '0011_auto_20200204_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtinmap',
            name='password',
            field=models.CharField(blank=True, help_text='The Password for the VRS Router.', max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='gtinmap',
            name='path',
            field=models.CharField(blank=True, help_text="The Sub Path of the VRS Service. For Example: If the URL path is http://vrs.qu4rtet.io/vrs, then the path is: /vrs. The compliant portion of the path, e.g. /verify/ or /checkConnectivity/ etc., is NOT required here, unless the path is NOT GS1 Compliant as indicated int 'GS1 Compliant' field below.", max_length=256, null=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='gtinmap',
            name='user_name',
            field=models.CharField(blank=True, help_text='The Username for the VRS Router.', max_length=100, null=True, verbose_name='Username'),
        ),
    ]
