# Generated by Django 3.0.5 on 2020-07-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0009_auto_20200221_1039'),
        ('quartet_vrs', '0012_auto_20200204_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtinmap',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routing Maps'},
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'verbose_name': 'Verification Request', 'verbose_name_plural': 'Verification Requests'},
        ),
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted', models.BooleanField(default=True, help_text='Whether or not this company has query access.', verbose_name='Access Granted')),
                ('company', models.ForeignKey(help_text='A company as identified by its GLN.', on_delete=django.db.models.deletion.CASCADE, to='quartet_masterdata.Company')),
                ('responder', models.ForeignKey(help_text='The responder GLN for this company will be determined  by this mapping if not the system default.  Leave blank to use the default responder in settings.', on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='quartet_masterdata.Company', verbose_name='Responder')),
            ],
        ),
    ]
