# Generated by Django 3.0.5 on 2020-07-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0009_auto_20200221_1039'),
        ('quartet_vrs', '0013_auto_20200730_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccess',
            options={'verbose_name': 'Query Access', 'verbose_name_plural': 'Query Access'},
        ),
        migrations.AlterField(
            model_name='companyaccess',
            name='responder',
            field=models.ForeignKey(blank=True, help_text='The responder GLN for this company will be determined  by this mapping if not the system default.  Leave blank to use the default responder in settings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='quartet_masterdata.Company', verbose_name='Responder'),
        ),
    ]
